### ISSUE TITLE
Implement Phase 2 EMTF++

### ISSUE THREAD

**Issue by jiafulow** [jiafulow/L1TriggerSep2016#46]
Implement Phase 2 EMTF++ in CMSSW, which currently exists as a set of Python scripts.

**Comment by jiafulow** [comment]
Part 1 has been submitted: https://github.com/cms-l1t-offline/cmssw/pull/779 . It is sync'ed to https://github.com/jiafulow/L1TriggerSep2016/pull/51 .

**Comment by jiafulow** [comment]
Part 2 has been submitted: https://github.com/cms-l1t-offline/cmssw/pull/780 . It was ported from v2.0.0 L1TMuonSimulationsMar2017 .

**Comment by jiafulow** [comment]
Part 3 has been submitted: https://github.com/cms-l1t-offline/cmssw/pull/784 . It was sync'ed to 78bf25c94ffbc3d5ee0fcdd660fe0f4dad0eb99a , which was the HEAD of the 'phase2-develop' branch. It only includes some minor C++ optimizations such as the use of constexpr's. This should be the final PR for this EMTF++ development cycle.

**Comment by rekovic** [comment]
@jiafulow 
Thank you.

**Comment by jiafulow** [comment]
EMTF++ Sep 2019 update has been submitted: https://github.com/cms-l1t-offline/cmssw/pull/802 . It was sync'ed to c48d8283317f3407a798c93a8fce9fda62b27e9e , which was the HEAD of the 'phase2-develop' branch. This C++ version was based on the L1TMuonSimulationsMar2017 python script 'rootpy_trackbuilding11.py' v3.1.0.

**Comment by jiafulow** [comment]
EMTF++ Oct 2019 update has been submitted: https://github.com/cms-l1t-offline/cmssw/pull/826 . It was sync'ed to ca717516c10deda73cdc8cc3a39c7cfcfcc547d7 , which was the HEAD of the 'phase2-develop' branch. This C++ version was based on the L1TMuonSimulationsMar2017 python script 'rootpy_trackbuilding11.py' v3.2.0.
